version: "3"
services:
  weeve-weevagator:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      EGRESS_API_HOST: "https://hookb.in/pzaBWG9rKoSXNNqwBo3o"
      EGRESS_API_METHOD: "POST"
      HANDLER_HOST: "0.0.0.0"
      HANDLER_PORT: "5000"
      INTERVAL_UNIT: "ms"
      INTERVAL_PERIOD: 10000
      FUNCTION: "mean"
      INPUT_LABEL: "temperature"
      DATA_TYPE: "float"
      OUTPUT_LABEL: "differentialTemp"
      OUTPUT_UNIT: "Celsius"
    ports:
      - 5000:5000