version: "3.0"
services:
  aggregator:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
        MODULE_NAME: "aggregator"
        MODULE_TYPE: "Processing"
        INGRESS_HOST: "0.0.0.0"
        INGRESS_PORT: "80"
        EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
        INTERVAL_UNIT: "ms"
        INTERVAL_PERIOD: 10000
        FUNCTION: "mean"
        INPUT_LABEL: "temperature"
        OUTPUT_LABEL: "differentialTemp"
    ports:
      - 80:80
